name: Daily Activity Tracker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script to generate daily log
      run: python scripts/generate_log.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.name "Eric Idogun" 
        git config --local user.email "idogunoghenetega@gmail.com"
        git add daily_logs/
        git commit -m "Create daily log for $(date '+%Y-%m-%d')" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/tegaidogun/daily-activity-tracker.git

